In [3]:
import tensorflow as tf

c:\anaconda3\envs\tf\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
x = [[1,2,3],[10,20,30]]
x2 = [[0,0,1],[1,2,3]]

In [5]:
temp1 = tf.constant(x)
temp2 = tf.constant(x2)

In [6]:
res1 = temp1 - temp2
res2 = tf.subtract(temp1 , temp2)
res3 = tf.reduce_sum(res1 , axis = 1)
res4 = tf.reduce_sum(res1 , axis = 0)

In [7]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    r1,r2,r3,r4 = sess.run([res1,res2,res3,res4])
    print(r1)
    print(r2)
    print(r3)
    print(r4)

[[ 1  2  2]
 [ 9 18 27]]
[[ 1  2  2]
 [ 9 18 27]]
[ 5 54]
[10 20 29]


---
### Triplet Losdd Teset

In [8]:
def triplet_loss2(y_pred, alpha = 0.2): 
    anchor, positive, negative = y_pred[0], y_pred[1], y_pred[2]
    
    pos_dist1 = tf.reduce_sum( tf.square( anchor - positive) , axis = 1)    
    neg_dist1 = tf.reduce_sum(tf.square(anchor - negative) , axis = 1)
    basic_loss1 = tf.add( tf.subtract(pos_dist1 , neg_dist1) , alpha)
    loss1 = tf.reduce_mean( tf.maximum(basic_loss1 , 0.0) , axis = 0)
    
    pos_dist2 = tf.square(anchor - positive)
    neg_dist2 = tf.square(anchor - negative)
    basic_loss2 = tf.reduce_sum(pos_dist2-neg_dist2)+alpha
    loss2 = tf.reduce_sum(tf.maximum(basic_loss2,0.))
    
    
    pos_dist3 = tf.reduce_sum( tf.square(anchor - positive))
    neg_dist3 = tf.reduce_sum( tf.square(anchor - negative))
    basic_loss3 = tf.add(tf.subtract(pos_dist3, neg_dist3), alpha)
    loss3 = tf.maximum(tf.reduce_mean(basic_loss3), 0.0)

    return pos_dist1 , pos_dist2 , pos_dist3 , neg_dist1 , neg_dist2,neg_dist3,basic_loss1, basic_loss2,basic_loss3 , loss1 , loss2 , loss3

In [9]:
sess =tf.Session()
tf.set_random_seed(1)
y_pred1 = (tf.random_normal([3, 12], mean=6, stddev=0.1, seed = 1),
              tf.random_normal([3, 12], mean=1, stddev=1, seed = 1),
              tf.random_normal([3, 12], mean=3, stddev=4, seed = 1))
    
y_pred2 = (tf.random_normal([3, 12], mean=6, stddev=0.1, seed = 1),
              tf.random_normal([3, 12], mean=1, stddev=1, seed = 1),
              tf.random_normal([3, 12], mean=3, stddev=4, seed = 1))
    
y_pred2 = (tf.random_normal([3, 12], mean=6, stddev=0.1, seed = 1),
              tf.random_normal([3, 12], mean=1, stddev=1, seed = 1),
              tf.random_normal([3, 12], mean=3, stddev=4, seed = 1))

In [ ]:
print()